sudo: false
language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
install:
  - npm install
script:
- npm run lint
git - npm run build
- npm run lint-functions

notifications:
  slack: blackturtleneck:EVLbkltY4ixRldvU557yRFpb

