sudo: false
language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
<<<<<<< HEAD
install:
  - npm install
=======
>>>>>>> 9e1e7fabba8369987c6a0e30f1071ff038a1c198
script:
- npm run lint
- npm test
- npm run build
- npm run lint-functions
<<<<<<< HEAD
notifications:
  slack: blackturtleneck:EVLbkltY4ixRldvU557yRFpb
=======
>>>>>>> 9e1e7fabba8369987c6a0e30f1071ff038a1c198
