language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm run lint
- npm test
- npm run build
- npm run lint-functions
 notifications:
    slack: blackturtleneck:5UGXE5FSGS7FyRVRdWDT20DW